import { readFile, writeFile } from 'fs/promises';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { APP_VERSION } from './src/config/appVersion.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(__dirname, 'src');

const FILES = [
  'parse/parser.js',
  'config/fiscalCalendar.js',
  'config/planAmountUtils.js',
  'config/expandConfig.js',
  'config/visibilityConfig.js',
  'config/rowDisplayConfig.js',
  'config/journalDefinitionConfig.js',
  'config/expenseAccountConfig.js',
  'config/bsBalanceSheetAccountConfig.js',
  'config/expenseSortConfig.js',
  'config/sectionColorConfig.js',
  'config/sectionFilterConfig.js',
  'config/uiColorConfig.js',
  'parse/parseJournal.js',
  'parse/aggregateFormula.js',
  'parse/journalDrilldown.js',
  'csv/csvNameConfig.js',
  'config/consumptionTaxRateConfig.js',
  'config/withholdingTaxRateConfig.js',
  'config/legalWelfareRateConfig.js',
  'config/taxSimulationConfig.js',
  'config/employeeConfig.js',
  'config/salaryPlanConfig.js',
  'config/planCellEdit.js',
  'config/taxPaymentConfig.js',
  'config/expensePlanOverrideConfig.js',
  'config/outsourcingPlanConfig.js',
  'config/revenuePlanConfig.js',
  'config/planKpiConfig.js',
  'config/uiTooltipConfig.js',
  'config/appVersion.js',
  'enrich/enrichUtils.js',
  'enrich/planEmployeeSalaryRows.js',
  'enrich/planTaxPaymentRows.js',
  'enrich/planOutsourcingRows.js',
  'enrich/planRevenueRows.js',
  'enrich/planMiscIncomeRows.js',
  'enrich/planPeriodAverageFill.js',
  'enrich/corporateTaxItemized.js',
  'enrich/nextPeriodTaxForecast.js',
  'enrich/planCashFlowOpening.js',
  'enrich/planCashFlowForecast.js',
  'parse/parseEmployee.js',
  'config/monthDisplayConfig.js',
  'config/planPeriodCleanup.js',
  'config/viewportScale.js',
  'config/appSettings.js',
  'config/settingsExport.js',
  'csv/csvFolder.js',
  'csv/csvLoader.js',
  'ui/planSettingsTableUi.js',
  'ui/revenueSettings.js',
  'ui/journalDefinitionSettings.js',
  'ui/expensePlanOverrideSettings.js',
  'ui/uiColorPanel.js',
  'ui/colorSettingsWindow.js',
  'ui/dashboard.js',
  'ui/taxForecastSettingsUi.js',
  'ui/taxForecastWindow.js',
  'ui/plan.js',
];

const VERSION_MARKER_RE = /<!--APP_VERSION-->[\s\S]*?<!--\/APP_VERSION-->/g;
const VERSION_DOC_FILES = ['README.md', 'manual.html'];

function stripModuleSyntax(code) {
  return code
    .replace(/^import\s[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^export\s*\{[^}]+\}\s*from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^export\s*\{[^}]+\};?\s*$/gm, '')
    .replace(/^export\s+(async\s+)?/gm, '$1')
    .replace(/^export\s+(const|let|var)\s+/gm, '$1 ')
    .trim();
}

/** README / 取扱説明書 の <!--APP_VERSION--> マーカーへ表示バージョンを同期する */
async function syncAppVersionDocs(version) {
  const replacement = `<!--APP_VERSION-->${version}<!--/APP_VERSION-->`;
  for (const rel of VERSION_DOC_FILES) {
    const path = resolve(__dirname, rel);
    const before = await readFile(path, 'utf8');
    if (!VERSION_MARKER_RE.test(before)) {
      throw new Error(`${rel} に <!--APP_VERSION--> マーカーがありません`);
    }
    VERSION_MARKER_RE.lastIndex = 0;
    const after = before.replace(VERSION_MARKER_RE, replacement);
    if (after !== before) {
      await writeFile(path, after, 'utf8');
      console.log(`Synced APP_VERSION (${version}) -> ${rel}`);
    }
  }
}

/** IIFE 連結後に衝突するトップレベル名を検出する（モジュール境界が消えるため） */
function assertNoBundleNameCollisions(fileCodes) {
  const map = new Map();
  const re = /^(?:export\s+)?(?:async\s+)?function\s+(\w+)|^(?:export\s+)?(?:const|let|var)\s+(\w+)\s*=/gm;
  for (const { file, code } of fileCodes) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(code))) {
      const name = m[1] || m[2];
      if (!map.has(name)) map.set(name, []);
      map.get(name).push(file);
    }
  }
  const collisions = [...map.entries()].filter(([, files]) => new Set(files).size > 1);
  if (collisions.length === 0) return;
  const detail = collisions
    .map(([name, files]) => `  ${name}: ${[...new Set(files)].join(', ')}`)
    .join('\n');
  throw new Error(`Bundle top-level name collision(s):\n${detail}`);
}

await syncAppVersionDocs(APP_VERSION);

const fileCodes = [];
for (const file of FILES) {
  const code = await readFile(resolve(srcDir, file), 'utf8');
  fileCodes.push({ file, code });
}
assertNoBundleNameCollisions(fileCodes);

const parts = fileCodes.map(
  ({ file, code }) => `/* ${file} */\n${stripModuleSyntax(code)}`,
);

const outPath = resolve(srcDir, 'plan.bundle.js');
const bundle = `/* Auto-generated by build.mjs — do not edit */\n(function () {\n'use strict';\n\n${parts.join('\n\n')}\n})();\n`;

await writeFile(outPath, bundle, 'utf8');
execSync('node scripts/check-encoding.mjs', { stdio: 'inherit' });
execSync(`node --check "${outPath}"`, { stdio: 'inherit' });
console.log('Built src/plan.bundle.js');
