import { readFile, writeFile } from 'fs/promises';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(__dirname, 'src');

const FILES = [
  'parse/parser.js',
  'config/expandConfig.js',
  'config/visibilityConfig.js',
  'config/rowDisplayConfig.js',
  'config/expenseAccountConfig.js',
  'config/expenseSortConfig.js',
  'config/sectionColorConfig.js',
  'config/uiColorConfig.js',
  'parse/parseJournal.js',
  'parse/aggregateFormula.js',
  'parse/journalDrilldown.js',
  'csv/csvNameConfig.js',
  'config/consumptionTaxRateConfig.js',
  'config/withholdingTaxRateConfig.js',
  'config/legalWelfareRateConfig.js',
  'config/employeeConfig.js',
  'config/salaryPlanConfig.js',
  'config/taxPaymentConfig.js',
  'config/outsourcingPlanConfig.js',
  'enrich/planEmployeeSalaryRows.js',
  'enrich/planTaxPaymentRows.js',
  'enrich/planOutsourcingRows.js',
  'enrich/planPeriodAverageFill.js',
  'parse/parseEmployee.js',
  'config/appSettings.js',
  'csv/csvFolder.js',
  'csv/csvLoader.js',
  'ui/plan.js',
];

function stripModuleSyntax(code) {
  return code
    .replace(/^import\s[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^export\s*\{[^}]+\}\s*from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^export\s*\{[^}]+\};?\s*$/gm, '')
    .replace(/^export\s+(async\s+)?/gm, '$1')
    .replace(/^export\s+(const|let|var)\s+/gm, '$1 ')
    .trim();
}

const parts = [];
for (const file of FILES) {
  const code = await readFile(resolve(srcDir, file), 'utf8');
  parts.push(`/* ${file} */\n${stripModuleSyntax(code)}`);
}

const outPath = resolve(srcDir, 'plan.bundle.js');
const bundle = `/* Auto-generated by build.mjs — do not edit */\n(function () {\n'use strict';\n\n${parts.join('\n\n')}\n})();\n`;

await writeFile(outPath, bundle, 'utf8');
execSync('node scripts/check-encoding.mjs', { stdio: 'inherit' });
execSync(`node --check "${outPath}"`, { stdio: 'inherit' });
console.log('Built src/plan.bundle.js');
